services:
  - type: web
    name: cloud-security-web
    env: python
    branch: main
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn cloud_security.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        fromDatabase: false
        value: "django-insecure-cloud-security-hybrid-dl-2026-key-change-in-production"
      - key: DEBUG
        fromDatabase: false
        value: "False"
    plan: free